version: '3.9'

services:
  my_postgres_db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432/tcp"
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - my_network
  server:
    build:
      context: ..
      dockerfile: docker/server/Dockerfile
    container_name: server 
    networks:
      - my_network
    depends_on:
      - my_postgres_db
    environment:
      APP_PORT: ${APP_PORT}
      PORT_POSTGRES: ${POSTGRES_PORT}
      HOST_POSTGRES: ${POSTGRES_HOST}
      USER_POSTGRES: ${POSTGRES_USER}
      PASSWORD_POSTGRES: ${POSTGRES_PASSWORD}
      DB_NAME_POSTGRES: ${POSTGRES_DB}
      URL_POSTGRES: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
    restart: always
    ports:
      - '${APP_PORT}:8080'

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
